package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.NBATeam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NBATEAM".
*/
public class NBATeamDao extends AbstractDao<NBATeam, Long> {

    public static final String TABLENAME = "NBATEAM";

    /**
     * Properties of entity NBATeam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Team_name = new Property(1, String.class, "team_name", false, "TEAM_NAME");
        public final static Property Icon_url = new Property(2, String.class, "icon_url", false, "ICON_URL");
        public final static Property Icon_id = new Property(3, Integer.class, "icon_id", false, "ICON_ID");
    };


    public NBATeamDao(DaoConfig config) {
        super(config);
    }
    
    public NBATeamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NBATEAM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TEAM_NAME\" TEXT," + // 1: team_name
                "\"ICON_URL\" TEXT," + // 2: icon_url
                "\"ICON_ID\" INTEGER);"); // 3: icon_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NBATEAM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NBATeam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String team_name = entity.getTeam_name();
        if (team_name != null) {
            stmt.bindString(2, team_name);
        }
 
        String icon_url = entity.getIcon_url();
        if (icon_url != null) {
            stmt.bindString(3, icon_url);
        }
 
        Integer icon_id = entity.getIcon_id();
        if (icon_id != null) {
            stmt.bindLong(4, icon_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public NBATeam readEntity(Cursor cursor, int offset) {
        NBATeam entity = new NBATeam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // team_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // icon_url
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // icon_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NBATeam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTeam_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIcon_url(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIcon_id(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(NBATeam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(NBATeam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
