package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NBATEAM".
 */
public class NBATeam {

    private Long id;
    private String team_name;
    private String icon_url;
    private Integer icon_id;

    public NBATeam() {
    }

    public NBATeam(Long id) {
        this.id = id;
    }

    public NBATeam(Long id, String team_name, String icon_url, Integer icon_id) {
        this.id = id;
        this.team_name = team_name;
        this.icon_url = icon_url;
        this.icon_id = icon_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTeam_name() {
        return team_name;
    }

    public void setTeam_name(String team_name) {
        this.team_name = team_name;
    }

    public String getIcon_url() {
        return icon_url;
    }

    public void setIcon_url(String icon_url) {
        this.icon_url = icon_url;
    }

    public Integer getIcon_id() {
        return icon_id;
    }

    public void setIcon_id(Integer icon_id) {
        this.icon_id = icon_id;
    }

}
